package LeetCode.bitManipulation.FindTheDifference_389;

/*
389. Find the Difference
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one
more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/
public class Solution {
    public char findTheDifference(String s, String t) {
        int buff = 0;
        for(char c : t.toCharArray()) buff ^= (int)c;
        for(char c : s.toCharArray()) buff ^= (int)c;
        return (char)buff;
    }
}